### ISSUE TITLE
Pricing Strips Limited to 12 mo multiples

### ISSUE THREAD

**Issue by neliaser** [neliaser/pri-reports#8]
In order to contrast with what we're actually doing for the client now, unless the client starts in the middle of a year, we should have the priced ranges be in one-year multiples.

This means that for SAV-E, the fixed price should be for a Jan-Dec contract. For SAV-G, it should be for an Apr-Mar contract.

Unless the client starts at a time of year off of that cycle, we should have a contrasting fixed price that matches the relevant one-year contract. 

So, if a client started a few years back, and we request a SAV-G for Jan 20-Mar 21, the actual performance of Jan 20-Mar 20 section of that should be contrasted with a price obtained for Apr 19-Mar 20, so that the contrast price isn't artificially inflated for corresponding only to the three winter months.

However, a client who actually originally started with PRI in Jan 2020 would have a three month strip for the fixed price. If we're looking at doing a Jan 20-Dec 20 report for them, it should show the three-month Jan-Mar 20 fixed price and a 12-mo Apr 20-Mar 21 price being contrasted with the relevant report months.

**Comment by chaimgertsberg** [comment]
Would this same logic be applied to the end of the year as well? If a SAV-G report is supposed to be from Jan 2020 to Dec 2020, would the fixed price strips be Apr 2019 - Mar 2020 and Apr 2020 to Mar 2021? If so, what if the data does not exist yet?

**Comment by neliaser** [comment]
We do have the strip prices for purchasing whatever the strip is back on the months when a comparable contract was actually purchased. What we can't do is project future actual savings. We're using that Apr-Mar year price for the contrast price.

So, if our analysis was supposed to be on savings from Jan 2020-Jun 2021, we would look at the Apr 2019-Mar 2020 strip prices for Jan 2020-Mar 2020, the Apr 2020-Mar 2021 prices for that timeframe, and the Apr 2021-Mar 2022 strip prices for contrasting Apr 2021-Jun 2021.

**Comment by cdizzle97** [comment]
Makes sense, I just wanted to make sure. I pushed this change, so it should behave as described above.

**Comment by neliaser** [comment]
Just checked with the test case that would apply to this and to #12 and another test case that applies just to this, using the code at https://github.com/neliaser/pri-reports/blob/V-3.0/SavingsAnalysis%203.0.ps1 (assuming that's the latest one you pushed; the timing matched your comment).

I still get the same result as cited in #12, with a period from Apr 2020-Dec 2014 [sic] when running an Apr 2020-Mar 2021 analysis for 209 East Lake Shore Ag.

When looking at the strip from Jan 2020-Jun 2021 for a client who was with us before Jan 2020, I expected to get contrasts with three pricing strips: Jan 20-Mar 20 would be contrasted with the pricing strip from Apr 19-Mar 20, Apr 20-Mar 21 with Apr 20-Mar 21, and Apr 21-Jun 21 with Apr 21-Mar 22. (If that doesn't make sense, let's talk on the phone or Zoom.)

Only two strips are shown in the report, rather than three. I haven't checked on whether the first calculated market price references Apr 19-Mar 20, though it might.

![image](https://user-images.githubusercontent.com/82979133/130467024-4c7728dd-3e54-4546-8fba-c91eed0fe4db.png)

**Comment by cdizzle97** [comment]
This also appears to be because the usage data ends early
![image](https://user-images.githubusercontent.com/7708015/130708346-7c3c3ace-9ab1-4ed7-b634-842d47fc7ab2.png)
Below is the query that was run to calculate the price for 7/15/2019 in the first term:
SELECT max_price, cast(date_pr AS DATE) AS date_pr FROM (
    SELECT (MAX(price) + 0.3)/10 AS max_price, SUBSTRING(MAX(CONCAT(price, date_pr)), 14) AS date_pr FROM(
    SELECT price.date_pr AS date_pr, AVG(price.price + basis.price) AS price
        FROM pricing.fwd_price_g price
        INNER JOIN pricing.fwd_price_basis basis ON (price.date_pr = basis.date_pr && price.yr = basis.yr && price.mo = basis.mo)
    WHERE ((MONTH(price.date_pr) = 7 && YEAR(price.date_pr) = 2019) && utility_id = 50010 && ((price.yr = 2019 && (price.mo >= 4 && price.mo <= 12))
    || (price.yr > 2019 && price.yr < 2020) || (price.yr = 2020 && (price.mo >= 1 && price.mo <= 3)))) GROUP BY date_pr) intermediate ) intermediate2

Based on this, it looks like it is properly contrasting the first three months with Apr 19-Mar 20
